### ISSUE TITLE
Use AccessibleTime

### ISSUE THREAD

**Issue by anthonygego** [darkyne/INGInious-upcoming-tasks#1]
https://github.com/darkyne/INGInious-upcoming-tasks/blob/9a4e8651db67a22dabaf73b1b88fc0f15e2c52ef/inginious_upcoming_tasks/__init__.py#L52

You should probably use the AccessibleTime class (or improve it if required) here, instead

**Comment by darkyne** [comment]
Now using:
`from inginious.frontend.accessible_time import parse_date`
But I still have to transform no-deadline tasks into year 9999 deadline to easily compare them.
I hope this is not a problem ?
This is because task without deadline would return "no deadline" (based on language) when calling get_deadline() which is harder to filter compared to generic:
`deadline > datetime.now()+timedelta(days=time_planner)`

**Comment by anthonygego** [comment]
You can improve AccessibleTime so that it implements the comparison operators. This way you do not have to hardcode 9999, a no deadline task will always be higher in time.

**Comment by darkyne** [comment]
You mean: to implement a comparator that would compare two datetimes in general case or one datetime and one string always considering the datetime < the string  ?
I am not sure it is really better than what I do now which is:
```python
   if task.get_accessible_time().is_always_accessible():
        return parse_date("18/03/9999 12:00:00", "%d/%m/%Y %H:%M:%S")
    elif task.get_accessible_time().is_never_accessible():
        return parse_date("18/03/9999 12:00:00", "%d/%m/%Y %H:%M:%S")
    else:
        return parse_date(task.get_deadline())

**Comment by anthonygego** [comment]
Whatever, as long as there is no more ``parse_date`` which should be encapsulated in AccessibleTime, and ideally no hardcoding of 9999. Even if we don't expect to be used these days, this is quite a bad practice.

**Comment by darkyne** [comment]
Damn, you are right...
Actually I didn't notice the:
`get_soft_end_date(self)`
method in AccessibleTime class...
So actually it was possible to directly return the datetime item without requiring to parse it back from a string...
Thanks
