### ISSUE TITLE
Do not rely on specific dispenser functions

### ISSUE THREAD

**Issue by anthonygego** [darkyne/INGInious-upcoming-tasks#2]
https://github.com/darkyne/INGInious-upcoming-tasks/blob/9a4e8651db67a22dabaf73b1b88fc0f15e2c52ef/inginious_upcoming_tasks/__init__.py#L221

The ``add_task`` and ``remove_task`` functions are specific to dispensers using Sections. You may want to use the Sections templating tools. Directly use the Jinja templates for this, but not Python functions that may not be available for every task dispenser.

**Comment by darkyne** [comment]
Thanks for the feedback.
Indeed trying to use the exact same template as the one for displaying tasks in a course was a bad idea.
Actually it was possible to display tasks in a much simpler way without requiring sections or dispenser_data.
