### ISSUE TITLE
Comprehensions

### ISSUE THREAD

**Issue by anthonygego** [darkyne/INGInious-upcoming-tasks#3]
https://github.com/darkyne/INGInious-upcoming-tasks/blob/9a4e8651db67a22dabaf73b1b88fc0f15e2c52ef/inginious_upcoming_tasks/__init__.py#L134

It would be more idiomatic to use comprehensions here.

**Comment by darkyne** [comment]
Thanks for the review.
Replaced by:
```python
if (not any(task in tasks for task in tasks_data)):
    open_courses.pop(course.get_id())
